name: Build All Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: ':miuix:iosSimulatorArm64Test'
            os: macos-latest
          - target: ':miuix:desktopTest'
            os: ubuntu-latest
          - target: ':miuix:assembleAndroidTest'
            os: ubuntu-latest
          - target: ':miuix:testDebugUnitTest'
            os: ubuntu-latest
          - target: ':miuix:testReleaseUnitTest'
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run check
        if: matrix.os == 'macos-latest'
        run: ./gradlew check
      - name: Run test
        run: ./gradlew ${{ matrix.target }}
      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/**
